// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtMZZgD8s_1i9yZX7zi1ICtD4Mow5xJJI',
    appId: '1:716398334059:web:dc5706f1f06d48bc57e12e',
    messagingSenderId: '716398334059',
    projectId: 'flutter-ios-cooking-app',
    authDomain: 'flutter-ios-cooking-app.firebaseapp.com',
    storageBucket: 'flutter-ios-cooking-app.firebasestorage.app',
    measurementId: 'G-B0PDCD1X7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgeX1bWLxiwUKWD5mBnOETPSOtTlD4yuk',
    appId: '1:716398334059:android:4e778a38731ba6ab57e12e',
    messagingSenderId: '716398334059',
    projectId: 'flutter-ios-cooking-app',
    storageBucket: 'flutter-ios-cooking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEHjY_NweRxDFHsg2t4_q6dK_jPLCK4Mc',
    appId: '1:716398334059:ios:aa456d092f0a3b9057e12e',
    messagingSenderId: '716398334059',
    projectId: 'flutter-ios-cooking-app',
    storageBucket: 'flutter-ios-cooking-app.firebasestorage.app',
    iosBundleId: 'com.example.cooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEHjY_NweRxDFHsg2t4_q6dK_jPLCK4Mc',
    appId: '1:716398334059:ios:aa456d092f0a3b9057e12e',
    messagingSenderId: '716398334059',
    projectId: 'flutter-ios-cooking-app',
    storageBucket: 'flutter-ios-cooking-app.firebasestorage.app',
    iosBundleId: 'com.example.cooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtMZZgD8s_1i9yZX7zi1ICtD4Mow5xJJI',
    appId: '1:716398334059:web:543c9a154f61baf857e12e',
    messagingSenderId: '716398334059',
    projectId: 'flutter-ios-cooking-app',
    authDomain: 'flutter-ios-cooking-app.firebaseapp.com',
    storageBucket: 'flutter-ios-cooking-app.firebasestorage.app',
    measurementId: 'G-BHKVDNJYNT',
  );
}
